on: [repository_dispatch]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - id: show-payload
      run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
    - id: show-field
      run: 'echo "Foo field is: ${{ github.event.client_payload.foo }}"'
